### ISSUE TITLE
release files should be contained on "cxsast_custom_reporting" folder

### ISSUE THREAD

**Issue by marcgp** [cxpsemea/cxsast_custom_reporting#11]
**Describe the bug**
In order to better support a single location with multiple binaries, the release should be contained on a "cxsast_custom_reporting" folder

**Expected behavior**
after extracting the released zip file, the following structure should be present on the file system

```
cxsast_custom_reporting
    │   CHANGELOG.txt
    │   cxsast_custom_reporting_v1.0.0-next.3_win_x64.exe
    │   LICENSE.txt
    │   README.txt
    │
    └───config
        │   config.example.ini
        │
        └───templates
                ScanSummary.html
```

**Comment by hugomota** [comment]
This is already implemented on 8081f80d272177f4c9a47c7080e9374d52a3edd9
