### ISSUE TITLE
Consolidated: Fetched data doesn't match with the Cx generated report 

### ISSUE THREAD

**Issue by hugomota** [cxpsemea/cxsast_custom_reporting#22]
Currently, in some specific scans the fetched data from the database is not accurate.
The main issue is on the states tables.
Need to change the queries to use the stored procedures that Cx uses to generate the report.

**Comment by marcgp** [comment]
:information_source::information_source: **This issue has been fixed in [Release v1.2.3](https://github.com/cxpsemea/cxsast_custom_reporting/releases/tag/v1.2.3)**
